spring:
  datasource:
    username: root
    password: 13042001
    url: jdbc:mysql://localhost:3306/inventories
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8082